### ISSUE TITLE
Chapter 2, build.sbt

### ISSUE THREAD

**Issue by dholtz** [denisftw/event-sourcing-scala#1]
https://github.com/denisftw/event-sourcing-scala/blob/master/chapter_02/build.sbt

Relatively new to Scala and Play, and am working through your starter project.
I was unable to get the project to build based on the current form of the build.sbt.

I had to make the events module depend on root:
```
lazy val events = (project in file("events")).settings(commonSettings).
  settings(Seq(libraryDependencies := Seq(
    "com.typesafe.play" %% "play-json" % "2.5.9"
  ))).dependsOn(root)
```
Not sure if this is a legitimate issue or a lack of understanding on my part.

**Comment by denisftw** [comment]
Hi!

I've just tried it out and the second chapter compiles just fine without any changes. I remember a couple of days ago the Play team members said they were having troubles with DNS and the site was down. It could've affected their repositories as well, but it's hard to say for sure. Could you try it again and tell me the results?

The `events` project is definitely not supposed to depend on the `root`, because it should work the other way around. In theory, we can make `events` a completely separate module, publish it to the local repo or Bintray and then reference it in the dependencies section of the `root` project just like a regular library.

Thanks.
